# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Build and run tests"
  lane :test do
    scan
  end

  lane :beta do
    desc "TesfFlight for IOS"
    # Circle CI does not create new code signing certificates or provisioning profiles.
    sync_code_signing(type: "appstore", readonly: true)    # see code signing guide for more information, readonly because of CircleCI
    build_app(scheme: "DevOpsForRN")
    upload_to_testflight(skip_waiting_for_build_processing: true)
    # slack(
    #   slack_url: "https://hooks.slack.com/services/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"
    #   channel: "dev",
    #   message: "Successfully uploaded a fastlane beta release"
    # )
  end
end

